version: "1.55.2"

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gosec

run:
  go: "1.21"
  skip-dirs:
    - "vendor/"
    - "third_party/"
    - "testdata/"
    - "examples/"
    - "Godeps/"
    - "builtin/"
    - "/opt/homebrew/Cellar/go/"
