run:
  timeout: 5m

linters:
  enable:
    - gofmt
    - golint
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gosec

linters-settings:
  govet:
    check-shadowing: true
  gosec:
    excludes:
      - G404 # Use of weak random number generator

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
        - dupl
        - gosec

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
