apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: go-template
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-template
  template:
    metadata:
      labels:
        app: go-template
    spec:
      containers:
        - name: app
          image: go-template:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: GIN_MODE
              value: "release"
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: mongodb-uri
            - name: MONGODB_DB
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: mongodb-db
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
