server:
  port: 8080
  host: "0.0.0.0"
  read_timeout: 5s
  write_timeout: 10s
  idle_timeout: 120s

database:
  host: "localhost"
  port: 5432
  name: "mydb"
  user: "user"
  password: "password"

logging:
  level: "info"
  format: "json"
  output: "stdout"
