name: Create Repository from Template

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'New repository name'
        required: true
        type: string
      repo_description:
        description: 'Repository description'
        required: true
        type: string
      repo_visibility:
        description: 'Repository visibility'
        required: true
        type: choice
        options:
          - public
          - private
      owner:
        description: 'GitHub username or organization'
        required: true
        type: string

permissions:
  contents: write
  issues: write
  pull-requests: write
  repository-projects: write

jobs:
  create-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout template repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Create new repository and update files
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.REPO_CREATION_TOKEN }}
          script: |
            const repoName = context.payload.inputs.repo_name;
            const description = context.payload.inputs.repo_description;
            const visibility = context.payload.inputs.repo_visibility;
            const owner = context.payload.inputs.owner;
            
            // Create new repository
            const response = await github.rest.repos.createForAuthenticatedUser({
              name: repoName,
              description: description,
              private: visibility === 'private',
              auto_init: true
            });
            
            console.log(`Repository created: ${response.data.html_url}`);
            
            // Update repository settings
            await github.rest.repos.update({
              owner: owner,
              repo: repoName,
              allow_auto_merge: true,
              allow_merge_commit: true,
              allow_squash_merge: true,
              allow_rebase_merge: true,
              delete_branch_on_merge: true
            });
            
            // Create branch protection rules
            await github.rest.repos.updateBranchProtection({
              owner: owner,
              repo: repoName,
              branch: 'main',
              required_status_checks: null,
              enforce_admins: true,
              required_pull_request_reviews: {
                required_approving_review_count: 1
              },
              restrictions: null
            });
            
            // Create issue labels
            const labels = [
              { name: 'bug', color: 'd73a4a', description: 'Something isn\'t working' },
              { name: 'enhancement', color: 'a2eeef', description: 'New feature or request' },
              { name: 'documentation', color: '0075ca', description: 'Improvements or additions to documentation' },
              { name: 'good first issue', color: '7057ff', description: 'Good for newcomers' },
              { name: 'help wanted', color: '008672', description: 'Extra attention is needed' }
            ];
            
            for (const label of labels) {
              await github.rest.issues.createLabel({
                owner: owner,
                repo: repoName,
                name: label.name,
                color: label.color,
                description: label.description
              });
            }
            
            // Create initial issue
            await github.rest.issues.create({
              owner: owner,
              repo: repoName,
              title: 'Welcome to the project!',
              body: `## Getting Started\n\n1. Clone the repository\n2. Run \`go mod tidy\`\n3. Copy \`.env.example\` to \`.env\`\n4. Start coding!\n\n## Development\n\n- Follow the project structure\n- Write tests for new features\n- Update documentation as needed\n\n## Contributing\n\n1. Create a new branch\n2. Make your changes\n3. Submit a pull request\n\n## License\n\nThis project is licensed under the MIT License.`
            });
            
            // Copy files from template to new repository
            const fs = require('fs');
            const path = require('path');
            
            // Function to recursively copy files
            async function copyFiles(dir, baseDir = '') {
              const files = fs.readdirSync(dir);
              
              for (const file of files) {
                const filePath = path.join(dir, file);
                const relativePath = path.join(baseDir, file);
                const stats = fs.statSync(filePath);
                
                if (stats.isDirectory()) {
                  // Skip .git directory
                  if (file === '.git') continue;
                  await copyFiles(filePath, relativePath);
                } else {
                  // Skip certain files
                  if (file === '.env' || file === 'go.sum') continue;
                  
                  const content = fs.readFileSync(filePath, 'utf8');
                  let updatedContent = content;
                  
                  // Update module name in go.mod
                  if (file === 'go.mod') {
                    updatedContent = content.replace(
                      /module github\.com\/kishore-behera\/go-template-repo/,
                      `module github.com/${owner}/${repoName}`
                    );
                  }
                  
                  // Update README.md
                  if (file === 'README.md') {
                    updatedContent = content
                      .replace(/go-template-repo/g, repoName)
                      .replace(/Go Template Repository/g, description);
                  }
                  
                  try {
                    // Create or update file in the new repository
                    await github.rest.repos.createOrUpdateFileContents({
                      owner: owner,
                      repo: repoName,
                      path: relativePath,
                      message: `chore: add ${relativePath}`,
                      content: Buffer.from(updatedContent).toString('base64'),
                      branch: 'main'
                    });
                    console.log(`Added/updated file: ${relativePath}`);
                  } catch (error) {
                    console.error(`Error adding file ${relativePath}:`, error);
                  }
                }
              }
            }
            
            // Start copying files from the workspace
            await copyFiles('/github/workspace'); 